### ISSUE TITLE
Include VCAP_APPLICATION.application_id and VCAP_APPLICATION.instance_index in tracking payload

### ISSUE THREAD

**Issue by ptitzler** [IBM-Bluemix/cf-deployment-tracker-client-electron#1]
Include properties `application_id` and `instance_index` in tracking payload if it is defined by environment variable `VCAP_APPLICATION`. http://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#VCAP-APPLICATION
Example payload:
```
...
"application_id": "7a027268-2...5-468f-a3b8-feb3c3705c8c",
"instance_index": 0,
...

```

**Comment by glynnbird** [comment]
In an Electron app there won't be a VCAP_APPLICATION env variable (because it's not running in Bluemix) but I can add the properties `application_id` and `instance_index` as "" and 0 respectively?

**Comment by ptitzler** [comment]
I see, my bad. As a desktop app we probably shouldn't treat this like other DT clients because there's no Bluemix association. Without that association the two properties won't provide any additional insights in our analysis and adding them would not provide any obvious value.

**Comment by glynnbird** [comment]
Agreed. It's not really a "cf" project at all, but it's just following the same naming convention. I'll close this issue then :)
